In [9]:
import numpy as np

# Estructura del proyecto
1. Cargar datos
2. Revisar columnas
3. Preprocesamiento básico
4. Analizar ventas por categoría
5. Aplicar operaciones matemáticas adicionales

## Carga de Datos

Se utiliza `np.genfromtxt()` para cargar el archivo CSV.  
Como el dataset contiene columnas numéricas y de texto, se usa `dtype=None` para que NumPy detecte automáticamente los tipos de datos.

In [39]:
def cargar_datos(ruta_archivo):
    
    datos = np.genfromtxt(ruta_archivo,delimiter=",", names=True, dtype=None, encoding="utf-8")
    
    return datos

In [ ]:
ruta_archivo = "retail_sales_dataset.csv"

datos = cargar_datos(ruta_archivo)

print(datos[:5]) #se puso 5 para evitar mostrar todos los datos del archivo(modo de ejemplo)

[(1, '2023-11-24', 'CUST001', 'Male', 34, 'Beauty', 3,  50,  150)
 (2, '2023-02-27', 'CUST002', 'Female', 26, 'Clothing', 2, 500, 1000)
 (3, '2023-01-13', 'CUST003', 'Male', 50, 'Electronics', 1,  30,   30)
 (4, '2023-05-21', 'CUST004', 'Male', 37, 'Clothing', 1, 500,  500)
 (5, '2023-05-06', 'CUST005', 'Male', 30, 'Beauty', 2,  50,  100)]


In [40]:
ruta_archivo = "retail_sales_dataset.csv"

datos = cargar_datos(ruta_archivo)

print(datos[:5])

[(1, '2023-11-24', 'CUST001', 'Male', 34, 'Beauty', 3,  50,  150)
 (2, '2023-02-27', 'CUST002', 'Female', 26, 'Clothing', 2, 500, 1000)
 (3, '2023-01-13', 'CUST003', 'Male', 50, 'Electronics', 1,  30,   30)
 (4, '2023-05-21', 'CUST004', 'Male', 37, 'Clothing', 1, 500,  500)
 (5, '2023-05-06', 'CUST005', 'Male', 30, 'Beauty', 2,  50,  100)]


In [41]:
print(datos.dtype.names)

('Transaction_ID', 'Date', 'Customer_ID', 'Gender', 'Age', 'Product_Category', 'Quantity', 'Price_per_Unit', 'Total_Amount')


In [42]:
print("Cantidad de registros:", len(datos))
print("Columnas del dataset:")
print(datos.dtype.names)

print("Primeras 5 filas:")
print(datos[:5])

Cantidad de registros: 1000
Columnas del dataset:
('Transaction_ID', 'Date', 'Customer_ID', 'Gender', 'Age', 'Product_Category', 'Quantity', 'Price_per_Unit', 'Total_Amount')
Primeras 5 filas:
[(1, '2023-11-24', 'CUST001', 'Male', 34, 'Beauty', 3,  50,  150)
 (2, '2023-02-27', 'CUST002', 'Female', 26, 'Clothing', 2, 500, 1000)
 (3, '2023-01-13', 'CUST003', 'Male', 50, 'Electronics', 1,  30,   30)
 (4, '2023-05-21', 'CUST004', 'Male', 37, 'Clothing', 1, 500,  500)
 (5, '2023-05-06', 'CUST005', 'Male', 30, 'Beauty', 2,  50,  100)]


In [43]:
categorias = datos["Product_Category"]
cantidades = datos["Quantity"]
precios_unitarios = datos["Price_per_Unit"]
ventas_totales = datos["Total_Amount"]

# Ver categorías únicas

In [44]:
categorias_unicas = np.unique(categorias)

print("Categorías de productos:")
print(categorias_unicas)

Categorías de productos:
['Beauty' 'Clothing' 'Electronics']


# Calcular total de ventas por categoría


In [45]:
totales_por_categoria = []

for categoria in categorias_unicas:
    filtro = categorias == categoria
    total_categoria = np.sum(ventas_totales[filtro])
    totales_por_categoria.append(total_categoria)

totales_por_categoria = np.array(totales_por_categoria)

print("Categorías únicas:")
print(categorias_unicas)

print("Totales por categoría:")
print(totales_por_categoria)

Categorías únicas:
['Beauty' 'Clothing' 'Electronics']
Totales por categoría:
[143515 155580 156905]


# Promedio general de ventas

In [23]:
print("PROMEDIO DE VENTAS POR CATEGORÍA")

promedios_por_categoria = []

for categoria in categorias_unicas:
    filtro = categorias == categoria
    promedio_categoria = np.mean(ventas_totales[filtro])
    promedios_por_categoria.append(promedio_categoria)
    
    print(f"{categoria}: ${promedio_categoria:.2f}")

promedios_por_categoria = np.array(promedios_por_categoria)

PROMEDIO DE VENTAS POR CATEGORÍA
Beauty: $467.48
Clothing: $443.25
Electronics: $458.79


# Venta máxima

In [46]:
indice_mayor = np.argmax(totales_por_categoria)

categoria_mayor = categorias_unicas[indice_mayor]
venta_mayor = totales_por_categoria[indice_mayor]

print("Categoría con mayor venta:")
print(f"{categoria_mayor}: ${venta_mayor}")

Categoría con mayor venta:
Electronics: $156905


# Venta minima

In [28]:
indice_menor = np.argmin(totales_por_categoria)

categoria_menor = categorias_unicas[indice_menor]
venta_menor = totales_por_categoria[indice_menor]

print("Categoría con menor venta:")
print(f"{categoria_menor}: ${venta_menor}")

Categoría con menor venta:
Beauty: $143515


# Categoria clothing

In [35]:
categoria_buscada = "Clothing"

filtro_categoria = categorias == categoria_buscada

ventas_categoria = datos[filtro_categoria]

print(f"Ventas filtradas para la categoría: {categoria_buscada}")
print(ventas_categoria[:10])

Ventas filtradas para la categoría: Clothing
[( 2, '2023-02-27', 'CUST002', 'Female', 26, 'Clothing', 2, 500, 1000)
 ( 4, '2023-05-21', 'CUST004', 'Male', 37, 'Clothing', 1, 500,  500)
 ( 7, '2023-03-13', 'CUST007', 'Male', 46, 'Clothing', 2,  25,   50)
 (10, '2023-10-07', 'CUST010', 'Female', 52, 'Clothing', 4,  50,  200)
 (11, '2023-02-14', 'CUST011', 'Male', 23, 'Clothing', 2,  50,  100)
 (14, '2023-01-17', 'CUST014', 'Male', 64, 'Clothing', 4,  30,  120)
 (16, '2023-02-17', 'CUST016', 'Male', 19, 'Clothing', 3, 500, 1500)
 (17, '2023-04-22', 'CUST017', 'Female', 27, 'Clothing', 4,  25,  100)
 (19, '2023-09-16', 'CUST019', 'Female', 62, 'Clothing', 2,  25,   50)
 (20, '2023-11-05', 'CUST020', 'Male', 22, 'Clothing', 3, 300,  900)]


# Preprocesamiento básico

In [30]:
suma_total_ventas = np.sum(ventas_totales)
promedio_general_ventas = np.mean(ventas_totales)
venta_maxima = np.max(ventas_totales)
venta_minima = np.min(ventas_totales)
total_productos_vendidos = np.sum(cantidades)

print(f"Suma total de ventas: ${suma_total_ventas}")
print(f"Promedio general de ventas: ${promedio_general_ventas:.2f}")
print(f"Venta máxima registrada: ${venta_maxima}")
print(f"Venta mínima registrada: ${venta_minima}")
print(f"Total de productos vendidos: {total_productos_vendidos}")

Suma total de ventas: $456000
Promedio general de ventas: $456.00
Venta máxima registrada: $2000
Venta mínima registrada: $25
Total de productos vendidos: 2514


In [31]:
total_calculado = cantidades * precios_unitarios

print("Total calculado con Quantity x Price_per_Unit:")
print(total_calculado[:10])

Total calculado con Quantity x Price_per_Unit:
[ 150 1000   30  500  100   30   50  100  600  200]


In [32]:
diferencia = ventas_totales - total_calculado

print("Diferencia entre Total_Amount y total calculado:")
print(diferencia[:10])

Diferencia entre Total_Amount y total calculado:
[0 0 0 0 0 0 0 0 0 0]


In [33]:
ingreso_promedio_por_unidad = suma_total_ventas / total_productos_vendidos

print(f"Ingreso promedio por unidad vendida: ${ingreso_promedio_por_unidad:.2f}")

Ingreso promedio por unidad vendida: $181.38
